### ISSUE TITLE
Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed

### ISSUE THREAD

**Issue by n-askarian** [GuessWhatGame/guesswhat#17]
Hi there
I've  read your papers and I am trying to run your code. I've got the following error.
Traceback (most recent call last):
  File "src/guesswhat/preprocess_data/extract_img_features.py", line 115, in <module>
    gpu_ratio = args.gpu_ratio)
  File "/home/user/guesswhat/src/generic/preprocess_data/extract_img_features.py", line 73, in extract_features
    for batch in tqdm(iterator):
  File "/home/user/.local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "/home/user/da33/Narjes/guesswhat/src/generic/data_provider/iterator.py", line 90, in next
    return self.__next__()
  File "/home/user/da33/Narjes/guesswhat/src/generic/data_provider/iterator.py", line 85, in __next__
    return self.process_iterator.next()
  File "/usr/local/anaconda/5.0.1-Python2.7-gcc5/envs/tensorflow-1.4/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed

 This problem will occur when the pooled methods are not in the top level of the module. As you already ran the code, I can't figure out the reason for this error. Can you guess where the problem is from? Could you please let me know what hardware you used to run your program?
Thanks

**Comment by fstrub95** [comment]
Can you try to run with python3?
Some parts of our code are no more compatible with python2...

**Comment by n-askarian** [comment]
Many thanks for your quick reply
Yes, Sure. Let me run it with python3 again.

Cheers,
Narjes
