### ISSUE TITLE
About pre-trained model

### ISSUE THREAD

**Issue by choys73** [GuessWhatGame/guesswhat#18]
Hi, I tried to run your code.
I ran the train-qgen-reinforce.py (with pre-trained model provided).
The initial score is similar to your  accuracy provided README.
I have a question. Is the pre-trained model supervised model?
If NOT (Pre-trained = RL model), where (or HOW) can I get the Supervised model?
(I want to try my reinforcement learning model on pre-trained supervised learning model)

**Comment by fstrub95** [comment]
Hi Cho, 
The pre-trained models are the supervised model.
In order to apply RL methods on a large action space, you need an initial policy. This policy is obtained through a pre-training of the network.
Kind regards, 
Florian

**Comment by choys73** [comment]
Thank you for your kindness!

**Comment by choys73** [comment]
Hi,  I have some questions about your code. I read your code overall.

1.
I wanted to run my reinforcement learning model on your supervised model, so I ran the file(train_qgen_reinforce.py) which is modified(Just change the '-continue_exp' is False). 
#train_qgen_reinforce.py
    parser.add_argument("-continue_exp", type=bool, default=False, help="Continue previously started experiment?")
I thought it would be ok, but I got some error.

(NotFoundError (see above for traceback): Key qgen/rl_baseline/baseline_out/W not found in checkpoint
    [[Node: save/RestoreV2_6 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_6/tensor_names, save/RestoreV2_6/shape_and_slices)]]
    [[Node: save/RestoreV2/_11 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_36_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]])

I want to run basic looper without your pre-trained looper parameter.
What can i do for that?

2. When I read your report and code(qgen_lstm_network.py), I realized that your proposed algorithm(reinforcement) is similar with Actor-Critic Algorithm than REINFORCE. 
In your code qgen_lstm_network.py
line 158 ~ 160

# Policy gradient loss
                    rewards *= self.answer_mask[:, 1:]
                    self.score_function = tf.multiply(self.log_of_policy, rewards - self.baseline)  # score function

                    self.baseline_loss = tf.reduce_sum(tf.square(rewards - self.baseline))


I understood that Q-function is maybe "rewards" and Value Function is  "self.baseline"

Furthermore, In your code train_qgen_reinforce.py has "-no_thread" which looks like A3C algorithm.

Is this right?

**Comment by fstrub95** [comment]
Hi Cho, 
Regarding point1: this fix should work
https://github.com/GuessWhatGame/guesswhat/commit/ea11385326d85ddcfd9d2bba8a5aa5b3870a7dc3

In some python version, the argparse seems to be buggy while using boolean.  
You can print the value of args.load_checkpoint to check whether your arguments are correctly set.

Regarding policy loss, we are using reinforce with a baseline.
It is very similar than A2C but:
 - we are training our baseline with RMSE, not with TD(0) error. Thus, the baseline is NOT a value function. So, this is not an actor-critic (among other reasons). Say differently, we are not relying on the Bellman assumption to compute hte baseline.
 - we performed a full rollout, we do not perform bootstraping (as opposed to A2C that use TD(n) error)
 - our code is multi-threaded, but it is synchronous. So, this is different from A3C.

I agree that those differences may sound a bit small, but from RL perspective, this may have a huge impact. (Convergence guarantee, variance etc.)

**Comment by choys73** [comment]
Thank you for your reply. I understand the answer about question #2. 
However, the same problem still occurs in question # 1. I don't know what checkpoint means in this error. I would like to train my model without your pretrained looper parameters.
Please tell me how.

**Comment by fstrub95** [comment]
can you send me the stdout/stderr + pprint argparse
Kind regards

**Comment by choys73** [comment]
When I add the print(args), result is Namespace(config='config/looper/config.json', continue_exp=False, crop_dir='data/ft_vgg_crop', data_dir='data/', dict_file='dict.json', evaluate_all=False, exp_dir='out/loop/', gpu_ratio=0.95, guesser_identifier='e2c11b1757337d7969dc223c334756a9', img_dir='data/ft_vgg_img', networks_dir='out/', no_thread=2, oracle_identifier='156cb3d352b97ba12ffd6cf547281ae2', qgen_identifier='867d59b933a89f4525b189da9d67f17b', skip_training=False, store_games=True)

And error is 
INFO:tensorflow:Restoring parameters from out/qgen/867d59b933a89f4525b189da9d67f17b/params.ckpt
Restoring parameters from out/qgen/867d59b933a89f4525b189da9d67f17b/params.ckpt
2018-02-28 22:11:51.421242: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
2018-02-28 22:11:51.427681: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_out/W not found in checkpoint
2018-02-28 22:11:51.427865: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_hidden/W not found in checkpoint
2018-02-28 22:11:51.434676: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_out/b not found in checkpoint
2018-02-28 22:11:51.435094: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
2018-02-28 22:11:51.435772: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
2018-02-28 22:11:51.435814: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
2018-02-28 22:11:51.437825: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
2018-02-28 22:11:51.441898: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
2018-02-28 22:11:51.463617: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
Traceback (most recent call last):
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
	 [[Node: save/RestoreV2_2/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_46_save/RestoreV2_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/guesswhat/train/train_qgen_reinforce.py", line 178, in <module>
    qgen_saver.restore(sess, os.path.join(args.networks_dir, 'qgen', args.qgen_identifier, 'params.ckpt'))
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1560, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
	 [[Node: save/RestoreV2_2/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_46_save/RestoreV2_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'save/RestoreV2_5', defined at:
  File "src/guesswhat/train/train_qgen_reinforce.py", line 109, in <module>
    qgen_saver = tf.train.Saver(var_list=qgen_var)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 688, in build
    restore_sequentially, reshape)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 663, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ai8503/anaconda3/envs/GuessWhat/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Key qgen/rl_baseline/baseline_hidden/b not found in checkpoint
	 [[Node: save/RestoreV2_5 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_5/tensor_names, save/RestoreV2_5/shape_and_slices)]]
	 [[Node: save/RestoreV2_2/_21 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_46_save/RestoreV2_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
