### ISSUE TITLE
extract_img_features.py: cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed

### ISSUE THREAD

**Issue by ruizhaogit** [GuessWhatGame/guesswhat#6]
Hi Florian,

Thank you for the code!
I got an error when processing the images using "python2.7 src/guesswhat/preprocess_data/extract_img_features.py".

Load dataset -> set: valid
Traceback (most recent call last):
  File "src/guesswhat/preprocess_data/extract_img_features.py", line 132, in <module>
    for batch in iterator: #tqdm(iterator)
  File "/home/ubuntu/workspace/guesswhat/florian/guesswhat/src/generic/data_provider/iterator.py", line 90, in next
    return self.__next__()
  File "/home/ubuntu/workspace/guesswhat/florian/guesswhat/src/generic/data_provider/iterator.py", line 86, in __next__
    return self.process_iterator.next()
  File "/home/ubuntu/anaconda2/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed

Do you know how to solve this?

Best,
Rui

**Comment by ruizhaogit** [comment]
Error occurs with python2.7. It works with python3.
